# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixmulti<-function(A,B){
  return(A%*%B)
}

matrixmultinumber<-function(A,B){
  return(A*B)
}

matrixinv<-function(A){
  return(solve(A))
}

matrixtrans<-function(A){
  return(t(A))
}

matrixplus<-function(A,B){
  return(A+B)
}

matrixminu<-function(A,B){
  return(A-B)
}

matrixrow<-function(A,B){
  return(t(A[B+1,]))
}

rcpp_hello_world <- function() {
    .Call('admmquantile_rcpp_hello_world', PACKAGE = 'admmquantile')
}

generate_dataR <- function(dimnum, samplenum){
  library(MASS)
  return( .Call('generate_data', dimnum=dimnum, samplenum=samplenum, fun1=matrixmulti,fun2=matrixrow,fun2=matrixtrans))
}

example_admm_R <- function(fixedpart, exper_time, dimnum, samplenum, tau, gamma, lambda, z, r1, r2, q1, q2, w, X, Y){
  library(MASS)
  return( .Call('Example_of_admm', fixedpart=fixedpart, exper_time=exper_time, dimnum=dimnum, samplenum=samplenum, tau=tau, gamma=gamma, lambda=lambda, z=z, r1=r1, r2=r2, q1=q1, q2=q2, w=w, X=X, Y=Y, fun1=matrixmulti, fun2=matrixplus, fun3=matrixminu, fun4=matrixmultinumber, fun5=matrixtrans, fun6=matrixrow))
  
}

Example<-function(samplenum = 300,dimnum = 2000,exper_time = 5,r1=2,r2=1,tau=0.2,gamma=3.7,lambda=1){
  sampledata<-generate_dataR(dimnum = dimnum, samplenum = samplenum)
  beta_fixed_part<-diag(dimnum) - (r1/r2)*t(sampledata$X)%*%(solve(diag(samplenum)+(r1/r2)*sampledata$X%*%t(sampledata$X)))%*%sampledata$X
  result<-example_admm_R(fixedpart=beta_fixed_part, dimnum=dimnum, exper_time=exper_time, samplenum=samplenum, tau=tau, gamma=gamma, lambda=lambda, z=matrix(0,samplenum,1), r1=r1, r2=r2, q1=matrix(0,samplenum,1), q2=matrix(0,dimnum,1), w=matrix(0,dimnum,1), X=sampledata$X, Y=sampledata$Y)
  plot(result$beta_result,ylim=c(-2,2))
}